server:
  port: 10323

spring:
  profiles:
    active: dev
  application:
    name: garen-server
  datasource:
    url: jdbc:mysql://localhost:3306/garen
    username: root
    password: 1qaz@WSX
#top.binaryx.garen.server
logging:
  level:
    top.binaryx.garen.server.mapper: DEBUG
    root: INFO
